### PR TITLE
[breaking change] gettimeofday 2nd argument incorrect in some targets

### LINKED ISSUE #1338: gettimeofday has incorrect signature
The signature of `gettimeofday` incorrect on ~~most~~ all targets:

```
error: incompatible pointer types returning 'int (struct timeval *, struct timezone *)' from a function with result type 'int (*)(struct timeval *, void *)' [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return gettimeofday;
```

we should see if we can fix it. Will depend on how many crates are using it.

### PR DESCRIPTION
**Pull request by gnzlbg**
The second argument of `gettimeofday` was a `*mut c_void` on all targets,
but that type is incorrect in the following targets, where it should be
a `*mut timezone` instead:

On these other targets it appears that the signature of gettimeofday was incorrect (it takes a time-zone pointer instead of a void pointer):

*linux+gnu: http://man7.org/linux/man-pages/man2/gettimeofday.2.html
*freebsd: https://www.freebsd.org/cgi/man.cgi?query=gettimeofday&apropos=0&sektion=2&manpath=FreeBSD+11.2-stable&arch=default&format=html
*openbsd: https://man.openbsd.org/gettimeofday.2
*android: https://github.com/ricardoquesada/android-ndk/blob/master/usr/include/sys/time.h
*dragonfly: https://www.dragonflybsd.org/cgi/web-man?command=gettimeofday&section=2

This commit corrects the type on these targets, which is a breaking change. Due
to how this API is commonly used (e.g. passing `ptr::null_mut` to the second
argument), breakage should be minimal or non-existent (AFAICT only `time`, `libstd`, and `parking_lot` use this API, and they all should compile after this change). Users wanting to support both versions can just write `ptr as *mut _` instead.

Closes #1338.

---

On these targets, the signature of `gettimeofday` was correct (the second argument is a `void*`):

* macosx: https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/gettimeofday.2.html
* linux+musl: http://git.musl-libc.org/cgit/musl/tree/include/sys/time.h#n11
* linux+newlib: https://chromium.googlesource.com/native_client/nacl-newlib/+/99fc6c167467b41466ec90e8260e9c49cbe3d13c/newlib/libc/include/sys/time.h#74
* netbsd: http://netbsd.gw.com/cgi-bin/man-cgi?gettimeofday+2.i386+NetBSD-8.0
* newlib: https://github.com/devkitPro/newlib/blob/devkitA64/newlib/libc/include/sys/time.h#L370
* solaris/illumos: https://illumos.org/man/3C/gettimeofday
* emscripten: https://chromium.googlesource.com/external/github.com/kripken/emscripten/+/1.35.20/system/include/libc/sys/time.h#11

cc @alexcrichton

### CODE REVIEW

**Comment by gnzlbg** [comment]
@semarie thoughts about directly doing a breaking change for OpenBSD ?

@strangelittlemonkey @leo60228 ping on the breaking changes for newlib and dragonflybsd - you might need to patch libstd after this is released.

**Comment by gnzlbg** [comment]
So I just tried to update the crates depending on `gettimeofday` on the broken platforms, and there is nothing to update (most crates will continue to compile after the breaking change due to how this APIs are used) so I'm going to not provide a fallback here.

**Comment by gnzlbg** [comment]
cc @asomers since this is a breaking change on FreeBSD.

**Comment by semarie** [comment]
no problem for me with a breaking change. but it seems to me that if you removed the bad definition of `gettimeofday`, you not added it back for openbsd.

**Comment by alexcrichton** [comment]
I wouldn't personally consider this worth a breaking change, but I think it's fine to land. I do think though that it requires being pretty vigilant after the release and ready to revert if it causes undue breakage.

**Comment by gnzlbg** [comment]
I'll do a release with this change only once its ready, and submit a PR to rust-lang/rust to update libc.

File: src/unix/bsd/freebsdlike/freebsd/mod.rs [hunk 1]
```diff
@@ -1249,6 +1249,8 @@ f! {
 }
 
 extern {
+    pub fn gettimeofday(tp: *mut ::timeval,
```
Comment (asomers) [inline src/unix/bsd/freebsdlike/freebsd/mod.rs]: Why not combine FreeBSD's and Dragonfly's definitions in src/unix/bsd/freebsdlike/mod.rs ?

**Comment by leo60228** [comment]
Looks good. FWIW, that's the Linux-specific time header in newlib, the actual one is here: https://github.com/devkitPro/newlib/blob/devkitA64/newlib/libc/include/sys/time.h#L370

**Comment by leo60228** [comment]
Wait, I misunderstood what the commit did. It should be void* on newlib.

**Comment by gnzlbg** [comment]
thanks @leo60228 for taking a look, i've updated the PR, rebased, and all seems green. 

@bors: r+
