### PR TITLE
Unified all Linux sockopts definitions by arch

### LINKED ISSUE #2133: SO_INCOMING_CPU not defined for s390x-unknown-linux-gnu
I am trying to compile nb-connect 1.1.0 (which pulls in socket2 0.4.0) on Fedora Rawhide, but the build fails with `SO_INCOMING_CPU` not being defined in `libc` on i686 (fixed with libc 0.2.92) and s390x. I see that this constant was only very recently added to libc:

- https://github.com/rust-lang/libc/pull/2115
- https://github.com/rust-lang/libc/pull/2119
- https://github.com/rust-lang/libc/pull/2123
- https://github.com/rust-lang/libc/pull/2124

But the constant has not been added to s390x-unknown-linux-gnu yet.

### PR DESCRIPTION
**Pull request by zonyitoo**
- ref rust-lang/socket2#213

Fixes #2133

### CODE REVIEW

File: src/unix/linux_like/linux/gnu/b32/sparc/mod.rs [hunk 1]
```diff
@@ -340,6 +340,7 @@ pub const SO_OOBINLINE: ::c_int = 0x100;
 pub const SO_LINGER: ::c_int = 128;
 pub const SO_REUSEPORT: ::c_int = 0x200;
 pub const SO_ACCEPTCONN: ::c_int = 0x8000;
+pub const SO_INCOMING_CPU: ::c_int = 49;
```
Comment (JohnTitor) [inline src/unix/linux_like/linux/gnu/b32/sparc/mod.rs:343]: This isn't `0x0033`?

**Review by JohnTitor — CHANGES_REQUESTED** [review]
I think we can declare `SO_INCOMING_CPU` as 49 on musl and uclibc regardless of the arch, cannot we? I'd like to declare this on `linux/mod.rs` with a cfg for the sparc targets.

File: src/unix/linux_like/linux/gnu/b32/sparc/mod.rs (hunk 1 above)
Comment (zonyitoo) [reply src/unix/linux_like/linux/gnu/b32/sparc/mod.rs:343]: Yes, my fault.

**Comment by JohnTitor** [comment]
What the target depends on `parisc`? AFAIK sparc and parisc have a different value but other arch/env has `49` as a value so it shouldn't be difficult to gate with cfg.

**Comment by zonyitoo** [comment]
I have no idea. I don't know if there are other arch/env has different values right now or in the future.

Anyway, I am not familiar with `uClibc`. I just downloaded [its latest release](https://www.uclibc.org/) and couldn't find any related definition about `SO_INCOMING_CPU`. Could we make an accumption that this value is only defined in Linux Kernal headers?

**Comment by JohnTitor** [comment]
Creating PRs one by one to fix builds is not reasonable, and not gating it with a cfg or defining it for all linux_like/linux targets at once increases review/maintenance costs. And I'm not sure why you put it to each uclibc file instead of mod.rs as it should be the same value for all the uclibc from what I see https://doc.rust-lang.org/nightly/rustc/platform-support.html.

**Comment by zonyitoo** [comment]
```rust
cfg_if! {
    if #[cfg(target_arch = "parisc")] {
        // arch/parisc/include/uapi/asm/socket.h
        pub const SO_INCOMING_CPU = 0x402A;
    } else if #[cfg(target_arch = "sparc")] {
        // arch/sparc/include/uapi/asm/socket.h
        pub const SO_INCOMING_CPU = 0x0033;
    } else {
        // include/uapi/asm-generic/socket.h
        // arch/alpha/include/uapi/asm/socket.h
        // tools/include/uapi/asm-generic/socket.h
        // arch/mips/include/uapi/asm/socket.h
        pub const SO_INCOMING_CPU = 49;
    }
}
```

Should I put this block in `linux/mod.rs` and delete all the current `SO_INCOMING_CPU`?

**Comment by JohnTitor** [comment]
AFAIK we don't have any `parisc` arch targets so the first cfg is meaningless, right? And the second cfg doesn't catch sparc64 but it should, I think. Once it's done, yeah, we can clean-up it from subdirs. If something is wrong, CI will catch it (if the target is tested) so let's give it a try.

**Comment by JohnTitor** [comment]
Oh, I just mean we clean-up `SO_INCOMING_CPU` only, but it's now great clean-up. I really need #2109 to get merged first, to ensure all the things aren't broken...
Meanwhile, let's @bors try to see if the build is fine.

**Comment by zonyitoo** [comment]
Ah... Ok. Well, you can just merge #2109 and I will rebase my branch.

This is quite a big change. I have checked several times with my eyes but ... you should double check again.

**Comment by zonyitoo** [comment]
What does this build fail mean?

**Comment by JohnTitor** [comment]
> 
> 
> What does this build fail mean?

That's because Cirrus CI re-scheduled the jobs, @bors try

**Comment by JohnTitor** [comment]
The failure is:
```
error: use of deprecated type alias `unix::linux_like::linux::musl::time_t`: This type is changed to 64-bit in musl 1.2.0, we'll follow that change in the future release. See #1848 for more info.
  --> src/unix/linux_like/linux/arch/mips/b32.rs:5:18
   |
5  |     if size_of::<::time_t>() == size_of::<::c_long>() {
   |                  ^^^^^^^^
   |
note: the lint level is defined here
  --> src/lib.rs:18:38
   |
18 | #![cfg_attr(libc_deny_warnings, deny(warnings))]
   |                                      ^^^^^^^^
   = note: `#[deny(deprecated)]` implied by `#[deny(warnings)]`

error: use of deprecated type alias `unix::linux_like::linux::musl::time_t`: This type is changed to 64-bit in musl 1.2.0, we'll follow that change in the future release. See #1848 for more info.
  --> src/unix/linux_like/linux/arch/mips/b32.rs:11:18
   |
11 |     if size_of::<::time_t>() == size_of::<::c_long>() {
   |                  ^^^^^^^^

error: use of deprecated type alias `unix::linux_like::linux::musl::time_t`: This type is changed to 64-bit in musl 1.2.0, we'll follow that change in the future release. See #1848 for more info.
  --> src/unix/linux_like/linux/arch/mips/b32.rs:17:18
   |
17 |     if size_of::<::time_t>() == size_of::<::c_long>() {
   |                  ^^^^^^^^

error: use of deprecated type alias `unix::linux_like::linux::musl::time_t`: This type is changed to 64-bit in musl 1.2.0, we'll follow that change in the future release. See #1848 for more info.
  --> src/unix/linux_like/linux/arch/mips/b32.rs:24:18
   |
24 |     if size_of::<::time_t>() == size_of::<::c_long>() {
   |                  ^^^^^^^^

error: use of deprecated type alias `unix::linux_like::linux::musl::time_t`: This type is changed to 64-bit in musl 1.2.0, we'll follow that change in the future release. See #1848 for more info.
  --> src/unix/linux_like/linux/arch/mips/b32.rs:30:18
   |
30 |     if size_of::<::time_t>() == size_of::<::c_long>() {
   |                  ^^^^^^^^

error: aborting due to 5 previous errors

error: could not compile `libc`
```

**Comment by zonyitoo** [comment]
Oh, you have merged that regression-test PR. Shoudl I rebase it?

**Comment by JohnTitor** [comment]
It's unnecessary; bors automatically rebases to master.

**Comment by zonyitoo** [comment]
I tried to rebase locally without any conflicts.

**Comment by JohnTitor** [comment]
It shouldn't have any conflicts, I mean, there's no need to rebase but you can if you like (or if you want to run it on your local).

**Comment by zonyitoo** [comment]
https://github.com/torvalds/linux/blob/master/arch/mips/include/uapi/asm/socket.h

They really exist. :(

**Comment by JohnTitor** [comment]
@bors delegate+

Feel free to test it on the try build.

**Comment by zonyitoo** [comment]
It said there were breaking changes for `aarch64` about constants: `SO_TIMESTAMP_NEW`, ..., `SO_DETACH_REUSEPORT_BPF`.

But other architectures doesn't have these in CI.

Should I add back them for `aarch64`?

**Comment by zonyitoo** [comment]
So it only exists in non-MUSL images.

```
The following warnings were emitted during compilation:

warning: /checkout/target/aarch64-unknown-linux-musl/debug/build/libc-test-bfda7340573bba60/out/main.c:39959:66: error: 'SO_TIMESTAMP_NEW' undeclared here (not in a function); did you mean 'SO_TIMESTAMPNS'?
warning: 39959 |             static const int __test_const_SO_TIMESTAMP_NEW_val = SO_TIMESTAMP_NEW;
warning:       |                                                                  ^~~~~~~~~~~~~~~~
warning:       |                                                                  SO_TIMESTAMPNS
warning: /checkout/target/aarch64-unknown-linux-musl/debug/build/libc-test-bfda7340573bba60/out/main.c:39965:68: error: 'SO_TIMESTAMPNS_NEW' undeclared here (not in a function); did you mean 'SO_TIMESTAMPNS'?
warning: 39965 |             static const int __test_const_SO_TIMESTAMPNS_NEW_val = SO_TIMESTAMPNS_NEW;
warning:       |                                                                    ^~~~~~~~~~~~~~~~~~
warning:       |                                                                    SO_TIMESTAMPNS
warning: /checkout/target/aarch64-unknown-linux-musl/debug/build/libc-test-bfda7340573bba60/out/main.c:39971:69: error: 'SO_TIMESTAMPING_NEW' undeclared here (not in a function); did you mean 'SO_TIMESTAMPING'?
warning: 39971 |             static const int __test_const_SO_TIMESTAMPING_NEW_val = SO_TIMESTAMPING_NEW;
warning:       |                                                                     ^~~~~~~~~~~~~~~~~~~
warning:       |                                                                     SO_TIMESTAMPING
warning: /checkout/target/aarch64-unknown-linux-musl/debug/build/libc-test-bfda7340573bba60/out/main.c:39977:65: error: 'SO_RCVTIMEO_NEW' undeclared here (not in a function); did you mean 'SO_RCVTIMEO'?
warning: 39977 |             static const int __test_const_SO_RCVTIMEO_NEW_val = SO_RCVTIMEO_NEW;
warning:       |                                                                 ^~~~~~~~~~~~~~~
warning:       |                                                                 SO_RCVTIMEO
warning: /checkout/target/aarch64-unknown-linux-musl/debug/build/libc-test-bfda7340573bba60/out/main.c:39983:65: error: 'SO_SNDTIMEO_NEW' undeclared here (not in a function); did you mean 'SO_SNDTIMEO'?
warning: 39983 |             static const int __test_const_SO_SNDTIMEO_NEW_val = SO_SNDTIMEO_NEW;
warning:       |                                                                 ^~~~~~~~~~~~~~~
warning:       |                                                                 SO_SNDTIMEO
warning: /checkout/target/aarch64-unknown-linux-musl/debug/build/libc-test-bfda7340573bba60/out/main.c:39989:73: error: 'SO_DETACH_REUSEPORT_BPF' undeclared here (not in a function); did you mean 'SO_ATTACH_REUSEPORT_CBPF'?
warning: 39989 |             static const int __test_const_SO_DETACH_REUSEPORT_BPF_val = SO_DETACH_REUSEPORT_BPF;
warning:       |                                                                         ^~~~~~~~~~~~~~~~~~~~~~~
warning:       |                                                                         SO_ATTACH_REUSEPORT_CBPF
warning: cc1: error: unrecognized command line option '-Wno-unknown-warning-option' [-Werror]
warning: cc1: all warnings being treated as errors
```

**Comment by zonyitoo** [comment]
@JohnTitor I think it is ready to be merged.

File: src/unix/linux_like/linux/arch/generic/b32.rs [hunk 2]
```diff
@@ -0,0 +1,39 @@
+// use core::mem::size_of;
+
+// sizeof(time_t) == sizeof(__kernel_long_t)
```
Comment (JohnTitor) [inline src/unix/linux_like/linux/arch/generic/b32.rs:3]: If we turn off this, then I don't think we should leave them?

Comment (zonyitoo) [reply src/unix/linux_like/linux/arch/generic/b32.rs:3]: Actually I think it should be turned on, but some of the kernels in CI doesn't support that. I left them here because sometime in the future we will need to turn it on.

Comment (JohnTitor) [reply src/unix/linux_like/linux/arch/generic/b32.rs:3]: Still, I'd like to remove it until we can actually import them to simplify code, our structure is complex currently so I don't want to make it any more complicated unless we have to.

Comment (zonyitoo) [reply src/unix/linux_like/linux/arch/generic/b32.rs:3]: Ok.

**Comment by JohnTitor** [comment]
Related Zulip topic: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Homu.20Stuck.3F
I'm holding off this until it's resolved.

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Awesome, thanks for the clean-up!
@bors r+

**Comment by Thomasdezeeuw** [comment]
Thanks for doing this @zonyitoo.
